Review ready
davisdambis/Embedding-Images-and-Video pull request #5
Opened 2020-01-17 08:45 UTC by davisdambis

Fixed changes needed for review

2020-01-17 09:19 UTC, fatymahmed reviewed
## Hi @davisdambis @BrittanyBlake,
Great job making the changes suggested in the previous review 👏👏. However, there are still a few things that you need to fix.

- Your recommended videos sidebar overlaps with the main video, please fix this.
- You could add some spacing between the logo and the main icon.
![screenshot](https://user-images.githubusercontent.com/16196289/72599847-823e9700-3923-11ea-8226-173433b5f095.png)
- Your search bar should have a `<button>` tag that represents the search button with has the search icon, [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/search_button_requirement.png) 
- Your pull request should have a description of what you've done so far, what you have implemented, please make it more descriptive. [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

[OPTIONAL]
- I noticed that this is your second review, in this case, it's a good idea to use the same pull request as the one you used for your first code review or you could add a link of the first pull request in this pull request. You can apply this to your upcoming projects.

2020-01-17 09:21 UTC, fatymahmed requested changes
### Kindly make the suggested changes and request for another code review.

## Status: Changes Required
_Feel free to reach out to me on slack (fatima) if you have any questions, I'd be happy to help._

2020-01-17 14:43 UTC, davisdambis commented
- fixed sidebar and video overlap

- added spacing between icon and main logo

- added button tag

2020-01-17 17:23 UTC, shshamim63 commented
## Status :heavy_check_mark:  [Approved] :heavy_check_mark: 
___
Hi @davisdambis  and @BrittanyBlake :wave: 
Great job so far :clap: You have covered all the changes asked by the previous reviewer. Project contains descriptive readme but the appearance needs some polishing. Check this [link](https://www.markdownguide.org/cheat-sheet/). I think you can use it to look it better. The UI contains all the parts. maybe you can improve it a little bit more. Especially the nav items. The text of the aside items are really small comparing to its image. But as you have covered all the minimal requirements I will approve this project.
___
#### This :+1: is from me. You can go ahead. Don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-01-17 19:21 UTC, addod19 requested changes
#### status: Require changes 🔴
Hi @davisdambis and @BrittanyBlake , 🙂
You have done a good job so far, there are few things we have to do to get this project approved check comment below : 🙂

- It has a <button> tag that represents the search button. The search button does not look good, let us improve it. [youtube.com](youtube.com)
- It has at least three images at the rightmost part of the navbar, which consist of icons and avatar. Currently you do not have the avatar on your page. Per theis requirement, it is assumed the user is logged in.
- It shows the avatar of the user who uploaded the image, currently we don't have this on our page. Let's add it.
- There is an horizontal scroll on the output of the page. Below is a screenshot of how it looks now:
![Screenshot from 2020-01-17 19-11-09](https://user-images.githubusercontent.com/46388113/72639203-f9dce800-395c-11ea-8f6b-8a9c3ea11eab.png)

This is due to giving a definite width to your main container. Let's give our main container a width of 100%.
- Let use fix the warnings return by [w3validator](https://validator.w3.org). They are warnings but easily fixable.
- Add descriptive pull request and summary.

Kindly make these changes and submit project for review 
Happy coding.

[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

2020-01-17 19:21 UTC, addod19 commented on index.html
> +    <section class="sidebar">
- Let improve the semantics by using ``` <aside>``` instead of ```<section class="sidebar">```

2020-01-20 08:04 UTC, davisdambis commented
We improved the search button and made changes to the project

2020-01-20 09:04 UTC, rOluochKe commented
@addod19 and @davisdambis merge your project and resubmit for review

2020-01-20 09:23 UTC, merged